<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <StaticWebAssetBasePath>App_Plugins/$(AssemblyName)</StaticWebAssetBasePath>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<None Include="$(OutputPath)\*.pdb" Pack="true" PackagePath="lib/$(TargetFramework)/" />
	</ItemGroup>


	<PropertyGroup>
    <VersionPrefix>15.1.0</VersionPrefix>
    <VersionSuffix Condition="'$(Configuration)'=='Debug'">build$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmm`))</VersionSuffix>
    <Authors>Anders Bjerner, Yevhen Savinov</Authors>
    <Company>Limbo</Company>
    <Title>Skybrud Redirects</Title>
    <Description>
		Redirects manager for Umbraco. If you are running your Umbraco on SQLite DB, mark the following columns as nullable in the SkybrudRedirects table after the first run:
		QueryString, DestinationQuery, DestinationFragment, DestinationCulture.

		A webhook to FE functionallity is available. To use it, you need to add the following app setting to your configuration:
		1. CustomSettings:Redirects:RedirectsWebhookUrl -- the URL of the webhook;
		2. CustomSettings:Redirects:RedirectsWebhookSecret -- the secret key for the webhook;
		It will send a POST request to the specified URL with the following JSON header:
		{
		"secret": "your_secret"
		}
		and the body will contain the following JSON object:
		{
		origin = "redirects"
		}
	</Description>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
  </PropertyGroup>

  <!-- Information for the NuGet package -->
  <PropertyGroup>
    <PackageId>Skybrud.Umbraco.Redirects</PackageId>
    <PackageTags>Umbraco, Redirects, Redirect, 301, 307, Content, Url, Skybrud, Limbo, Umbraco-Marketplace</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://packages.skybrud.dk/skybrud.umbraco.redirects/</PackageProjectUrl>
    <PackageIcon>Limbo.png</PackageIcon>
    <PackageReadmeFile>NUGET.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/skybrud/Skybrud.Umbraco.Redirects</RepositoryUrl>
  </PropertyGroup>

  <!-- Include NuGet dependencies -->
  <ItemGroup>
    <PackageReference Include="Skybrud.Essentials" Version="1.1.57" />
    <PackageReference Include="Umbraco.Cms.Api.Management" Version="15.1.2" />
    <PackageReference Include="Umbraco.Cms.Core" Version="15.1.2" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="15.1.2" />
  </ItemGroup>

  <!-- Include package icon and README for the NuGet package -->
  <ItemGroup>
    <Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
    <None Include="..\..\NUGET.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <!-- Generate XML documentation -->
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

</Project>